# <!-- Powered by BMAD™ Core -->
# Universal Market Intelligence System v4.0 Configuration
markdownExploder: true
projectType: market-intelligence
marketAnalysis:
  briefFile: docs/market-analysis-brief.md
  reportFile: docs/market-report.md
  samFile: docs/sam-calculation.xlsx
  knowledgeBase: docs/knowledge-base
dataValidation:
  definitionsLocation: .bmad-core/data/market-definitions-library.yaml
  validationLog: .ai/validation-log.md
qualityGates:
  checklistsLocation: .bmad-core/checklists
  gateResults: docs/quality-gates
customDocuments:
  - docs/market-structure-map.md
  - docs/opportunity-portfolio.md
  - docs/competitive-analysis.md
devLoadAlwaysFiles:
  - .bmad-core/data/market-definitions-library.yaml
  - .bmad-core/data/analysis-methodologies.yaml
devDebugLog: .ai/debug-log.md
projectStorageLocation: projects
slashPrefix: UMIS
